# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Sep 24 15:16:42 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        MainWindow.setMinimumSize(QtCore.QSize(400, 400))
        MainWindow.setMaximumSize(QtCore.QSize(400, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(4.0)
        MainWindow.setAnimated(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.parseButton = QtGui.QPushButton(self.centralwidget)
        self.parseButton.setEnabled(False)
        self.parseButton.setGeometry(QtCore.QRect(270, 300, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.parseButton.setFont(font)
        self.parseButton.setObjectName("parseButton")
        self.openButton = QtGui.QPushButton(self.centralwidget)
        self.openButton.setGeometry(QtCore.QRect(30, 20, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.openButton.setFont(font)
        self.openButton.setObjectName("openButton")
        self.startTimeLabel = QtGui.QLabel(self.centralwidget)
        self.startTimeLabel.setEnabled(False)
        self.startTimeLabel.setGeometry(QtCore.QRect(80, 220, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.startTimeLabel.setFont(font)
        self.startTimeLabel.setObjectName("startTimeLabel")
        self.endDateLabel = QtGui.QLabel(self.centralwidget)
        self.endDateLabel.setEnabled(False)
        self.endDateLabel.setGeometry(QtCore.QRect(240, 160, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.endDateLabel.setFont(font)
        self.endDateLabel.setObjectName("endDateLabel")
        self.startDateLabel = QtGui.QLabel(self.centralwidget)
        self.startDateLabel.setEnabled(False)
        self.startDateLabel.setGeometry(QtCore.QRect(80, 160, 66, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.startDateLabel.setFont(font)
        self.startDateLabel.setObjectName("startDateLabel")
        self.startDateCombo = QtGui.QComboBox(self.centralwidget)
        self.startDateCombo.setEnabled(False)
        self.startDateCombo.setGeometry(QtCore.QRect(60, 180, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.startDateCombo.setFont(font)
        self.startDateCombo.setMaxCount(1000000000)
        self.startDateCombo.setObjectName("startDateCombo")
        self.endDateCombo = QtGui.QComboBox(self.centralwidget)
        self.endDateCombo.setEnabled(False)
        self.endDateCombo.setGeometry(QtCore.QRect(220, 180, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.endDateCombo.setFont(font)
        self.endDateCombo.setObjectName("endDateCombo")
        self.endTimeLabel = QtGui.QLabel(self.centralwidget)
        self.endTimeLabel.setEnabled(False)
        self.endTimeLabel.setGeometry(QtCore.QRect(240, 220, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.endTimeLabel.setFont(font)
        self.endTimeLabel.setObjectName("endTimeLabel")
        self.excelCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.excelCheckBox.setEnabled(False)
        self.excelCheckBox.setGeometry(QtCore.QRect(20, 310, 241, 20))
        self.excelCheckBox.setVisible(True) ######################################################################
        self.excelCheckBox.setChecked(True) ######################################################################
        self.excelCheckBox.setObjectName("excelCheckBox")
        self.endTimeEdit = QtGui.QTimeEdit(self.centralwidget)
        self.endTimeEdit.setEnabled(False)
        self.endTimeEdit.setGeometry(QtCore.QRect(220, 240, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.endTimeEdit.setFont(font)
        self.endTimeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.endTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.endTimeEdit.setCurrentSection(QtGui.QDateTimeEdit.HourSection)
        self.endTimeEdit.setCalendarPopup(True)
        self.endTimeEdit.setObjectName("endTimeEdit")
        self.startTimeEdit = QtGui.QTimeEdit(self.centralwidget)
        self.startTimeEdit.setEnabled(False)
        self.startTimeEdit.setGeometry(QtCore.QRect(60, 240, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.startTimeEdit.setFont(font)
        self.startTimeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.startTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.startTimeEdit.setCurrentSection(QtGui.QDateTimeEdit.HourSection)
        self.startTimeEdit.setCalendarPopup(False)
        self.startTimeEdit.setObjectName("startTimeEdit")
        self.filterLine = QtGui.QFrame(self.centralwidget)
        self.filterLine.setEnabled(False)
        self.filterLine.setGeometry(QtCore.QRect(20, 130, 361, 20))
        self.filterLine.setFrameShape(QtGui.QFrame.HLine)
        self.filterLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.filterLine.setObjectName("filterLine")
        self.filterLabel = QtGui.QLabel(self.centralwidget)
        self.filterLabel.setEnabled(False)
        self.filterLabel.setGeometry(QtCore.QRect(30, 120, 151, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.filterLabel.setFont(font)
        self.filterLabel.setObjectName("filterLabel")
        self.changableLabel = QtGui.QLabel(self.centralwidget)
        self.changableLabel.setGeometry(QtCore.QRect(30, 70, 341, 41))
        self.changableLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.changableLabel.setObjectName("changableLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionTutorial = QtGui.QAction(MainWindow)
        self.actionTutorial.setObjectName("actionTutorial")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionTutorial)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.openButton, self.startDateCombo)
        MainWindow.setTabOrder(self.startDateCombo, self.endDateCombo)
        MainWindow.setTabOrder(self.endDateCombo, self.excelCheckBox)
        MainWindow.setTabOrder(self.excelCheckBox, self.parseButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Parse Running Wheel", None, QtGui.QApplication.UnicodeUTF8))
        self.parseButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Begin parsing data", None, QtGui.QApplication.UnicodeUTF8))
        self.parseButton.setStatusTip(QtGui.QApplication.translate("MainWindow", "Begin parsing data", None, QtGui.QApplication.UnicodeUTF8))
        self.parseButton.setText(QtGui.QApplication.translate("MainWindow", "Parse Data", None, QtGui.QApplication.UnicodeUTF8))
        self.openButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Import mouse running wheel data from a VitalView .asc  file", None, QtGui.QApplication.UnicodeUTF8))
        self.openButton.setStatusTip(QtGui.QApplication.translate("MainWindow", "Import mouse running wheel data from a VitalView .asc  file", None, QtGui.QApplication.UnicodeUTF8))
        self.openButton.setText(QtGui.QApplication.translate("MainWindow", "Open File", None, QtGui.QApplication.UnicodeUTF8))
        self.startTimeLabel.setText(QtGui.QApplication.translate("MainWindow", "Start Time", None, QtGui.QApplication.UnicodeUTF8))
        self.endDateLabel.setText(QtGui.QApplication.translate("MainWindow", "End Date", None, QtGui.QApplication.UnicodeUTF8))
        self.startDateLabel.setText(QtGui.QApplication.translate("MainWindow", "Start Date", None, QtGui.QApplication.UnicodeUTF8))
        self.startDateCombo.setToolTip(QtGui.QApplication.translate("MainWindow", "Select a starting date", None, QtGui.QApplication.UnicodeUTF8))
        self.startDateCombo.setStatusTip(QtGui.QApplication.translate("MainWindow", "Select a starting date", None, QtGui.QApplication.UnicodeUTF8))
        self.endDateCombo.setToolTip(QtGui.QApplication.translate("MainWindow", "Change the end date", None, QtGui.QApplication.UnicodeUTF8))
        self.endDateCombo.setStatusTip(QtGui.QApplication.translate("MainWindow", "Change the end date", None, QtGui.QApplication.UnicodeUTF8))
        self.endTimeLabel.setText(QtGui.QApplication.translate("MainWindow", "End Time", None, QtGui.QApplication.UnicodeUTF8))
        self.excelCheckBox.setToolTip(QtGui.QApplication.translate("MainWindow", "Uncheck to output to csv only", None, QtGui.QApplication.UnicodeUTF8))
        self.excelCheckBox.setStatusTip(QtGui.QApplication.translate("MainWindow", "Uncheck to output to csv only", None, QtGui.QApplication.UnicodeUTF8))
        self.excelCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Combine parsed data into Excel file", None, QtGui.QApplication.UnicodeUTF8))
        self.endTimeEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "Change end time (hh:mm:ss)", None, QtGui.QApplication.UnicodeUTF8))
        self.endTimeEdit.setStatusTip(QtGui.QApplication.translate("MainWindow", "Change end time (hh:mm:ss)", None, QtGui.QApplication.UnicodeUTF8))
        self.endTimeEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "hh:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.startTimeEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "Change start time (hh:mm:ss)", None, QtGui.QApplication.UnicodeUTF8))
        self.startTimeEdit.setStatusTip(QtGui.QApplication.translate("MainWindow", "Change start time (hh:mm:ss)", None, QtGui.QApplication.UnicodeUTF8))
        self.startTimeEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "hh:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.filterLabel.setText(QtGui.QApplication.translate("MainWindow", "Filter Data By  time", None, QtGui.QApplication.UnicodeUTF8))
        self.changableLabel.setText(QtGui.QApplication.translate("MainWindow", "Please start by loading a file ...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setToolTip(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setStatusTip(QtGui.QApplication.translate("MainWindow", "Import mouse running wheel data from a VitalView .asc  file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setToolTip(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setStatusTip(QtGui.QApplication.translate("MainWindow", "Quit this program", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setStatusTip(QtGui.QApplication.translate("MainWindow", "About this program", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTutorial.setText(QtGui.QApplication.translate("MainWindow", "Tutorial", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTutorial.setStatusTip(QtGui.QApplication.translate("MainWindow", "How to use this program", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

